#ifndef CONSTANTS_H
#define CONSTANTS_H

// BLOCKCHAIN
#define BLOCKCHAIN_VERSION "1.0"
#define CONSENSUS_MECHANISM "POW"

// BLOCK
#define DEFAULT_BLOCK_HASH_DIFFICULTY 5;  // uint32_t: simple #0s before hash
#define BLOCK_VERSION "1.0";

// TRANSACTION
#define TRANSACTION_VERSION "1.0";

#endif